<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <PackageId>A11yDefaults.Mvc</PackageId>
    <Description>Accessibility-first Tag Helpers and CSS defaults for ASP.NET Core MVC.</Description>
    <PackageTags>accessibility;a11y;aspnetcore;mvc;razor;wcag</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>a11y ronin</Authors>
    <Copyright>Copyright (c) 2026 tlex.dev</Copyright>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
